// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkjnkpuzymowxnpoynih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdram5rcHV6eW1vd3hucG95bmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzQ5NDksImV4cCI6MjA3MTQ1MDk0OX0.GzU0CoGdvF-6PLQQ4KpfblTbzqaKW58LTWb0pUJOC3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});